import type { AllowedSector } from '../types.ts';

/**
 * Canonical PDF/AcroForm field names that materially affect the VCs emitted by
 * `_verify`.
 *
 * The first 8 fields are the predefined annex fields generated by
 * `generateTermsAnnexPdf()`. The remaining fields are additional canonical
 * names already consumed by the verification flow when the PDF exposes visible
 * organization or representative identity.
 */
export const VerifyLegalOrgTermsPdfFieldName = {
  /** Organization profile tags; used as the organization additionalType string. */
  organizationAdditionalType: 'organization.additionalType',
  /** Main public organization identity reference or alternate canonical domain/DID. */
  organizationSameAs: 'organization.sameAs',
  /** Primary public organization domain. */
  organizationUrl: 'organization.url',
  /** Short display alias for the organization. */
  organizationAlternateName: 'organization.alternateName',
  /** Type/name of an optional external organization identifier. */
  organizationIdentifierType: 'organization.identifierType',
  /** Value for the optional external organization identifier. */
  organizationIdentifierValue: 'organization.identifierValue',
  /** @deprecated Legacy compatibility field. Prefer identifierType + identifierValue. */
  organizationRegistrationNumber: 'organization.registrationNumber',
  /** Organization controller email used for operational contact. */
  organizationControllerEmail: 'organization.contactPoint.email',
  /** Organization participant capability tokens. */
  organizationParticipantType: 'organization.participant.additionalType',
  /** Primary hosting organization domain. */
  organizationHostingUrl: 'organization.hostingOrganization.url',
  /** Hosting organization identifier, usually a tax/VAT-like identifier. */
  organizationHostingIdentifier: 'organization.hostingOrganization.identifier',
  /** Mandatory organization tax identifier. */
  organizationTaxID: 'organization.taxID',
  /** Registered legal name of the organization. */
  organizationLegalName: 'organization.legalName',
  /** @deprecated Alias kept for older consumers; use representativeLegalFullName. */
  organizationName: 'organization.name',
  /** Full legal representative name. */
  representativeLegalFullName: 'person.name',
  /** Representative identifier such as NIF/NIE. */
  representativeLegalIdentifier: 'person.identifier',
  /** Representative email / sameAs source used in the person credential. */
  representativeOfficialEmail: 'person.email',
  /** Representative given name. */
  representativeGivenName: 'person.givenName',
  /** Representative family name. */
  representativeFamilyName: 'person.familyName',
  /** @deprecated Alias kept for older consumers; use representativeOfficialEmail. */
  personEmail: 'person.email',
  /** @deprecated Alias kept for older consumers; use representativeLegalFullName. */
  representativeName: 'person.name',
  /** @deprecated Alias kept for older consumers; use representativeLegalIdentifier. */
  representativeIdentifier: 'person.identifier',
  /** @deprecated Alias kept for older consumers; use representativeLegalFullName/OfficialEmail. */
  personAlternateName: 'person.alternateName',
  /** @deprecated Alias kept for older consumers; use representativeGivenName. */
  personGivenName: 'person.givenName',
  /** @deprecated Alias kept for older consumers; use representativeFamilyName. */
  personFamilyName: 'person.familyName',
  /** @deprecated Alias kept for older consumers; use organizationParticipantType. */
  personAdditionalType: 'person.additionalType',
} as const;

/**
 * Legacy visible-label aliases accepted by extraction/parsing paths.
 *
 * These are intentionally separated from the schema-first canonical contract.
 */
export const VerifyLegalOrgTermsPdfLegacyAliasFieldName = {
  representativeLabelEs: 'Representante legal',
} as const;

/**
 * @deprecated Use `VerifyLegalOrgTermsPdfFieldName`.
 */
export const VerifyTermsPdfFieldName = VerifyLegalOrgTermsPdfFieldName;

export type VerifyLegalOrgTermsPdfFieldKey = keyof typeof VerifyLegalOrgTermsPdfFieldName;
export type VerifyLegalOrgTermsPdfFieldNameValue =
  typeof VerifyLegalOrgTermsPdfFieldName[VerifyLegalOrgTermsPdfFieldKey];

export type VerifyTermsPdfFieldNameValue =
  VerifyLegalOrgTermsPdfFieldNameValue;

/**
 * Primary typed shape of the legal organization PDF form, modeled like the
 * individual onboarding form contract.
 *
 * All fields are string-based because the PDF extraction layer yields raw text.
 * Runtime converters later map these values into schema.org Organization and
 * Person claims for the OrganizationCredential and LegalRepresentativeCredential.
 */
export interface LegalOrgFormTemplateFields {
  /** Organization profile tags carried forward into Organization.additionalType. */
  organizationAdditionalType?: string;
  /** Main public organization identity reference or alternate canonical domain/DID. */
  organizationSameAs?: string;
  /** Primary public organization domain. */
  organizationUrl?: string;
  /** Short display alias for the organization. */
  organizationAlternateName?: string;
  /** Type/name of an optional external organization identifier. */
  organizationIdentifierType?: string;
  /** Value for the optional external organization identifier. */
  organizationIdentifierValue?: string;
  /** Legacy compatibility field; prefer identifierType + identifierValue. */
  organizationRegistrationNumber?: string;
  /** Organization controller email used for operational contact. */
  organizationControllerEmail?: string;
  /** Organization participant capability tokens. */
  organizationParticipantType?: string;
  /** Primary hosting organization domain. */
  organizationHostingUrl?: string;
  /** Hosting organization identifier, usually a tax/VAT-like identifier. */
  organizationHostingIdentifier?: string;
  /** Mandatory organization tax identifier. */
  organizationTaxID?: string;
  /** Registered legal name of the organization. */
  organizationLegalName?: string;
  /** Full legal representative name. */
  representativeLegalFullName?: string;
  /** Representative identifier such as NIF/NIE. */
  representativeLegalIdentifier?: string;
  /** Representative email / sameAs source used in the person credential. */
  representativeOfficialEmail?: string;
  /** Representative given name. */
  representativeGivenName?: string;
  /** Representative family name. */
  representativeFamilyName?: string;
}

/**
 * @deprecated Use `LegalOrgFormTemplateFields`.
 */
export interface VerifyTermsPdfTemplateFields extends LegalOrgFormTemplateFields {}

export const VerifyTermsGeneratedAnnexFieldNames = Object.freeze([
  VerifyLegalOrgTermsPdfFieldName.organizationAdditionalType,
  VerifyLegalOrgTermsPdfFieldName.organizationSameAs,
  VerifyLegalOrgTermsPdfFieldName.organizationUrl,
  VerifyLegalOrgTermsPdfFieldName.organizationAlternateName,
  VerifyLegalOrgTermsPdfFieldName.organizationRegistrationNumber,
  VerifyLegalOrgTermsPdfFieldName.personEmail,
  VerifyLegalOrgTermsPdfFieldName.personAlternateName,
  VerifyLegalOrgTermsPdfFieldName.personAdditionalType,
] as const);

export const VerifyTermsIdentityPdfFieldNames = Object.freeze([
  VerifyLegalOrgTermsPdfFieldName.organizationTaxID,
  VerifyLegalOrgTermsPdfFieldName.organizationLegalName,
  VerifyLegalOrgTermsPdfFieldName.organizationName,
  VerifyLegalOrgTermsPdfFieldName.representativeLegalFullName,
  VerifyLegalOrgTermsPdfFieldName.representativeLegalIdentifier,
  VerifyLegalOrgTermsPdfFieldName.personGivenName,
  VerifyLegalOrgTermsPdfFieldName.personFamilyName,
] as const);

export const VerifyTermsPdfFieldNames = Object.freeze([
  ...VerifyTermsGeneratedAnnexFieldNames,
  ...VerifyTermsIdentityPdfFieldNames,
] as const);

export type VerifyTermsPdfFieldValue = string | undefined | null;

/**
 * Open raw field map extracted from the signed PDF.
 *
 * It intentionally stays open to unknown keys because real PDFs may expose
 * extra widgets, stale technical names, or visible labels that are not part of
 * the canonical contract.
 */
export type VerifyTermsPdfFieldMap = Readonly<
  LegalOrgFormTemplateFields
  & Partial<Record<VerifyTermsPdfFieldNameValue, VerifyTermsPdfFieldValue>>
  & Record<string, VerifyTermsPdfFieldValue>
>;

/**
 * Service capabilities that downstream GW onboarding commonly expects in the
 * emitted Organization VC `credentialSubject.makesOffer.serviceType`.
 *
 * Current ICA behavior:
 * - these values are not read from the annex AcroForm today
 * - they can be supplied through `organizationPayload.serviceType` or
 *   `organizationPayload.makesOffer.serviceType` in compat/demo flows
 */
export const VerifyTermsServiceCapability = {
  IndexReader: 'organization/Composition.rs',
  IndexProvider: 'organization/Composition.cruds',
  DigitalTwinReader: 'organization/ResearchSubject.rs',
  DigitalTwinProvider: 'organization/ResearchSubject.cruds',
} as const;

export type VerifyTermsServiceCapabilityValue =
  typeof VerifyTermsServiceCapability[keyof typeof VerifyTermsServiceCapability];

export type VerifyTermsServiceTypeInput =
  | VerifyTermsServiceCapabilityValue
  | VerifyTermsServiceCapabilityValue[]
  | string
  | string[];

/**
 * Human-friendly capability tokens that product/frontend may expose in UI.
 *
 * These are not the persisted values. Persisted values are the
 * `VerifyTermsServiceCapability.*` constants.
 */
export const VerifyTermsParticipantCapabilityToken = {
  IndexReader: 'IndexReader',
  IndexProvider: 'IndexProvider',
  DigitalTwinReader: 'DigitalTwinReader',
  DigitalTwinProvider: 'DigitalTwinProvider',
} as const;

export type VerifyTermsParticipantCapabilityTokenValue =
  typeof VerifyTermsParticipantCapabilityToken[keyof typeof VerifyTermsParticipantCapabilityToken];

/**
 * Mapping from UI/domain tokens into canonical `Service.serviceType` values.
 */
export const VerifyTermsParticipantCapabilityToServiceType = Object.freeze({
  [VerifyTermsParticipantCapabilityToken.IndexReader]: VerifyTermsServiceCapability.IndexReader,
  [VerifyTermsParticipantCapabilityToken.IndexProvider]: VerifyTermsServiceCapability.IndexProvider,
  [VerifyTermsParticipantCapabilityToken.DigitalTwinReader]: VerifyTermsServiceCapability.DigitalTwinReader,
  [VerifyTermsParticipantCapabilityToken.DigitalTwinProvider]: VerifyTermsServiceCapability.DigitalTwinProvider,
} as const);

/**
 * Product constraint for `participant.additionalType` interpreted as a
 * comma-separated list of capability tokens.
 *
 * Current agreed rules:
 * - max 2 values total
 * - max 1 token from Index family (Reader or Provider)
 * - max 1 token from DigitalTwin family (Reader or Provider)
 * - at least 1 token overall is required
 */
export const VerifyTermsParticipantAdditionalTypeRules = Object.freeze({
  maxItems: 2, // To be defined (select checkboxes for reader and provider in both individual and digital twin)
  indexFamily: [
    VerifyTermsParticipantCapabilityToken.IndexReader,
    VerifyTermsParticipantCapabilityToken.IndexProvider,
  ],
  digitalTwinFamily: [
    VerifyTermsParticipantCapabilityToken.DigitalTwinReader,
    VerifyTermsParticipantCapabilityToken.DigitalTwinProvider,
  ],
  requireAtLeastOneToken: true,
} as const);

/**
 * Compatibility payload accepted by `_verify` for Organization VC enrichment
 * when runtime policy allows unverified credential payloads.
 *
 * Signed PDF/certificate data remains the preferred production source.
 */
export interface VerifyTermsOrganizationPayloadCompatibilityFields {
  additionalType?: VerifyTermsServiceTypeInput; // comma-separated capabilities: IndexReader, IndexProvider, DigitalTwinReader, DigitalTwinProvider)
  contactPoint?: {
    email?: string; // legal representative email for controller binding/activation flows
  };
  legalName?: string;
  makesOffer?: {
    '@type'?: string;
    category?: AllowedSector | string;
  };
  memberOf:{
    hostingOrganization?: {
        taxID?: string;
        url?: string;
    };
  };
  sameAs?: string;
  taxID?: string;
  url?: string;
}

/**
 * Compatibility/demo payload accepted by `_verify` for the person VC.
 *
 * Current use in the backend:
 * - `name` and `identifier` can backfill representative identity in compat
 *   flows when the person identity must come from the document level
 * - `sameAs` and `email` are demo-only fallback sources for person VC
 *   `credentialSubject.sameAs`
 */
export interface VerifyTermsLegalRepresentativePayloadCompatibilityFields {
  name?: string;
  identifier?: string;
  givenName?: string;
  familyName?: string;
  sameAs?: string;
  email?: string;
}

/**
 * Frontend-friendly summary of the `_verify` inputs that materially affect:
 * - the emitted OrganizationCredential
 * - the emitted LegalRepresentativeCredential
 * - the ability to call `entity/did/document/_create` afterwards
 */
export interface VerifyTermsFrontendInputProfile {
  /**
   * Authoritative onboarding sector. This does not belong to the PDF fields.
   * It comes from the route path and feeds Organization VC
   * `credentialSubject.makesOffer.category` in demo fallback mode.
   */
  routeSector: AllowedSector;
  annexFields?: VerifyTermsPdfFieldMap;
  organizationPayload?: VerifyTermsOrganizationPayloadCompatibilityFields;
  legalRepresentativePayload?: VerifyTermsLegalRepresentativePayloadCompatibilityFields;
  /**
   * Preferred controller business/binding key source for later `_create`.
   * Send it in `_verify` as `body.data[].resource.controller.publicKeyJwk`.
   */
  controllerPublicKeyJwk?: Record<string, unknown>;
  /**
   * Optional organization credential-signing key bootstrap.
   * If omitted during `_verify`, ICA may generate an ES384 keypair and return
   * it in `_verify-response`.
   */
  organizationPublicKeyJwk?: Record<string, unknown>;
}

/**
 * Organization credential fields that GW flows should prefer once available in
 * emitted VCs.
 */
export interface VerifyTermsOrganizationCredentialFieldHints {
  /** Controller email for key-binding/activation workflows. */
  contactPointEmail?: string;
  /**
   * Participant role/capability tokens (comma-separated in VC additionalType).
   * UI tokens should be converted through
   * `VerifyTermsParticipantCapabilityToServiceType` when building
   * `Service.serviceType`.
   */
  participantAdditionalType?: string;
  /** Hosting endpoint (domain or IP) that will receive activation/transaction flows. */
  hostingOrganizationUrl?: string;
  /** VAT/tax identifier for the hosting provider organization. */
  hostingOrganizationIdentifier?: string;
  /** Dataspace sector/category. In ICA this is route-authoritative. */
  makesOfferCategory?: AllowedSector | string;
}

/**
 * Minimal checklist for callers that want `_verify` output to be reusable in
 * the later DID-document creation flow.
 */
export const VerifyTermsCreateReadiness = Object.freeze({
  authoritativeSectorSource: 'route',
  requiredPdfIdentityFieldsWhenCertificateOmitsOrganizationIdentity: [
    VerifyLegalOrgTermsPdfFieldName.organizationTaxID,
    VerifyLegalOrgTermsPdfFieldName.organizationLegalName,
  ],
  preferredControllerBindingPath: 'body.data[].resource.controller.publicKeyJwk',
  optionalOrganizationKeyAttachmentMediaType: 'application/jwk+json',
  organizationServiceTypePayloadPaths: [
    'organizationPayload.serviceType',
    'organizationPayload.makesOffer.serviceType',
  ],
} as const);

/**
 * TODO checklist for downstream GW implementations (`_activate` /
 * `_transaction`) once these fields are present in emitted VCs.
 */
export const VerifyTermsGwtemplateTodoChecklist = Object.freeze([
  'Prefer OrganizationCredential.credentialSubject.contactPoint.email as controller email when present.',
  'Fallback to LegalRepresentativeCredential identity only when OrganizationCredential contactPoint.email is missing.',
  'Interpret OrganizationCredential.credentialSubject.participant.additionalType as comma-separated capability tokens.',
  'Map participant.additionalType tokens to Service.serviceType canonical values using VerifyTermsParticipantCapabilityToServiceType.',
  'Enforce participant.additionalType rules: at least one token, max two total, max one per family (Index, DigitalTwin).',
  'Read OrganizationCredential.credentialSubject.hostingOrganization.url as hosting endpoint (domain/IP).',
  'Read OrganizationCredential.credentialSubject.hostingOrganization.identifier as hosting provider VAT/tax ID.',
  'Use OrganizationCredential.credentialSubject.makesOffer.category as onboarding sector/category for hosting registration context.',
] as const);
